# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf80a64ff8815ebf0fa3591adf07516a0283136d3c79bb14bfd68701c487d4621324bb05b49629285c729a9d3eab0a9a25ddff8d7942046d3caef93512d2674

test:
  secret_key_base: 317067fa8380609fb3f6ece636cd8840b3778f918770b63b4f47c4b6d31221a0988ac0a870f0da41298ac105f413ba8fc48a689bddfe288ce6a105b466752226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  

  # config.omniauth :facebook, "1366636660056640", "2fed8c5f13d3f982523509313bcf23e1"
  # config.omniauth :google_oauth2, "6216156229001-9euahq8u9d6874f9c2kmo7n159g0a4ui.apps.googleusercontent.com", "2HVxoFb8SbiP5HORcZOMKEJQ"
  # config.omniauth :kakao, "5d22190f869a8be19415a6d84e28d716", :redirect_path => "/users/auth/kakao/callback"
  # config.omniauth :naver, "eshEy9OT_VeUx9XvFdkt", "nJMKoleT_m"
  
#   echo "export Facebook_Key=1366636660056640" >> ~/.profile                          
#   echo "export Facebook_Secret=2fed8c5f13d3f982523509313bcf23e1" >> ~/.profile

# echo "export Google_Key=626156229001-9euahq8u9d6874f9c2kmo7n159g0a4ui.apps.googleusercontent.com" >> ~/.profile    
# echo "export Google_Secret=2HVxoFb8SbiP5HORcZOMKEJQ" >> ~/.profile      
 
# echo "export Kakao_Key=5d22190f869a8be19415a6d84e28d716" >> ~/.profile 

# echo "export Naver_Key=eshEy9OT_VeUx9XvFdkt" >> ~/.profile                         
# echo "export Naver_Secret=nJMKoleT_m" >> ~/.profile    

# source ~/.profile

